#!/bin/sh

if [ -n "$1" ]
then
    path="$1"
else
    path="."
fi

shift 1

while [ "$path" != / ] && [ -z "$searched" ]
do
    searched="$(find "$path" -maxdepth 1 -mindepth 1 "$@")"
    path="$(readlink -f "$path"/..)"
done

echo "$searched"
