#!/bin/sh

BIB_STR="$1"

BIB_ID_TYPE="$(python -c "import bibtexparser; entry = bibtexparser.bparser.BibTexParser(common_strings=True, ignore_nonstandard_types=False).parse(\"\"\"$BIB_STR\"\"\").entries[-1]; print(entry['ID']); print(entry['ENTRYTYPE']); print(entry['title'])")"
BIBID="$(echo "$BIB_ID_TYPE" | sed '1q;d')"
BIBTYPE="$(echo "$BIB_ID_TYPE" | sed '2q;d')"
BIBTITLE="$(echo "$BIB_ID_TYPE" | sed '3q;d' | sed -e "s/\\\\//g" | sed -e "s/://g")"

case "$BIBTYPE" in
    book)
        PDF_PATH="$ACADEMIC_DIRECTORY/bibliography/$BIBTYPE/$BIBTITLE.pdf"
        ;;
    *)
        PDF_PATH="$ACADEMIC_DIRECTORY/bibliography/$BIBTYPE/$BIBID.pdf"
        ;;
esac

echo "$PDF_PATH"
