#!/bin/sh

BIB_FILE="$1"
[ -f "$BIB_FILE" ] || exit 1

GLOBAL_BIB="$ACADEMIC_DIRECTORY/bibliography/library.bib"

[ "$BIB_FILE" = "$GLOBAL_BIB" ] && exit 1

BASE_DIR="$(dirname "$BIB_FILE")"

rm -rf "$BASE_DIR/bibliography"
mkdir -p "$BASE_DIR/bibliography"

python -c "
import bibtexparser

with open('$BIB_FILE', 'r') as bibfile:
    database = bibtexparser.bparser.BibTexParser(common_strings=True, ignore_nonstandard_types=False).parse_file(bibfile)

    for entry in database.entries:
        print(entry['ENTRYTYPE'], entry['ID'], entry['title'])" > temp_type_ids

while read -r TYPE_ID_TITLE
do
    TYPE="$(echo "$TYPE_ID_TITLE" | awk '{print $1}')"
    ID="$(echo "$TYPE_ID_TITLE" | awk '{print $2}')"
    TITLE="$(echo "$TYPE_ID_TITLE" | awk '{$1=$2=""; print substr($0,3)}')"

    mkdir -p "$BASE_DIR/bibliography/$TYPE"

    case "$TYPE" in
        book)
            NAME="$TITLE"
            ;;
        *)
            NAME="$ID"
            ;;
    esac

    ln -s "$ACADEMIC_DIRECTORY/bibliography/$TYPE/$NAME.pdf" "$BASE_DIR/bibliography/$TYPE/$NAME.pdf"
done < temp_type_ids

rm temp_type_ids
