#!/bin/sh


select_open () {
    BIB_FILE="$1"

    python -c "
import bibtexparser
import subprocess

def info_to_option(info: dict) -> str:
    return f\"[{info['ID']}] {info['title'].replace('{', '').replace('}', '')}\"

def select_result(matches: list[dict]) -> dict:
    try:
        options = {info_to_option(info): info for info in matches}

        options_process = subprocess.Popen(['echo', '-e', '\n'.join(options.keys())], stdout=subprocess.PIPE)
        selection_process = subprocess.Popen(['dmenu', '-i', '-l', '10'], stdin=options_process.stdout, stdout=subprocess.PIPE)

        selected = selection_process.communicate()[0].decode('utf-8', 'ignore').replace('\n', '')

        return options[selected]
    except (subprocess.CalledProcessError, KeyError):
        return {}


with open('$BIB_FILE', 'r') as bibfile:
    database = bibtexparser.bparser.BibTexParser(common_strings=True, ignore_nonstandard_types=False).parse_file(bibfile)

entry = select_result(database.entries)
if entry:
    db = bibtexparser.bibdatabase.BibDatabase()
    db.entries = [entry]
    print(bibtexparser.dumps(db))"
}

select_id () {
    BIB_FILE="$1"
    ID="$2"

    awk -v RS='' -v id="$ID" 'BEGIN{gsub(/\(|\)/,"\\\\&", id)} $0 ~ id' "$BIB_FILE"
}

open () {
    ID="$1"
    BIB_FILE="$2"

    if [ -z "$ID" ]
    then
        BIB_STR="$(select_open "$BIB_FILE")"
    else
        BIB_STR="$(select_id "$BIB_FILE" "$ID")"
    fi

    [ -z "$BIB_STR" ] && return 0

    PDF_PATH="$("$SCI_DIRECTORY/sci_pdf_path" "$BIB_STR")"

	if [ -f "$PDF_PATH" ]
	then
        xdg-open "$PDF_PATH"
	else
		notify-send "PDF unavailable."
	fi
}


ID="$1"

[ -f "$2" ] && BIB_FILE="$2"
GLOBAL_BIB="$ACADEMIC_DIRECTORY/bibliography/library.bib"

if [ -f "$BIB_FILE" ]
then
    open "$ID" "$BIB_FILE"
else
    open "$ID" "$GLOBAL_BIB"
fi

